name: Pressure Test
on:
  push:
jobs:
  pressure-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: go install github.com/rakyll/hey@latest
      - run: docker compose up --wait --detach --quiet-pull
      - run: "curl -si http://localhost:8000/example"
      - run: "~/go/bin/hey -H 'Authorization: Bearer foo' http://localhost:8000/example"
      - run: "curl -si http://localhost:8000/example"
      - run: docker compose logs
        if: ${{ always() }}
